// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxgrjruxwlywnwapnmhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14Z3JqcnV4d2x5d253YXBubWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NDM3NjYsImV4cCI6MjA1ODIxOTc2Nn0.9ORTyOp5ZVNLD6Gvbu-RSSeZEtIcgVmTaTJQNxFOHb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);